import os
from pathlib import Path
try:
    from dotenv import load_dotenv
    load_dotenv()
except ModuleNotFoundError:
    pass
BASE_DIR = Path(__file__).parent.parent
OPENAI_API_KEY: str = os.getenv('OPENAI_API_KEY', '')
OPENAI_BASE_URL = os.getenv('OPENAI_BASE_URL', 'https://api.openai.com/v1')
SERPAPI_KEY: str = os.getenv('SERPAPI_KEY', '')
SEARCH_URL = os.getenv('SEARCH_URL', '')
SEARCH_USER_ID = os.getenv('SEARCH_USER_ID', '')
SEARCH_APP_ID = os.getenv('SEARCH_APP_ID', '')
SEARCH_CHANNELS = [c.strip() for c in os.getenv('SEARCH_CHANNELS', 'news,report,announcement,teleconference').split(',') if c.strip()]
LLM_PROVIDER = os.getenv('LLM_PROVIDER', 'openai')
LITELLM_BASE = os.getenv('LITELLM_BASE', '')
LLM_MODEL = os.getenv('LLM_MODEL', 'gpt-4o-mini')
EMBED_MODEL = os.getenv('EMBED_MODEL', 'text-embedding-3-small')
EMBED_DIM = int(os.getenv('EMBED_DIM', '1536'))
OMNI_MODEL = os.getenv('OMNI_MODEL', 'gpt-4o-mini')
KB_CHUNK_SIZE = int(os.getenv('KB_CHUNK_SIZE', '512'))
KB_CHUNK_OVERLAP = int(os.getenv('KB_CHUNK_OVERLAP', '64'))
KB_EXTRACT_BATCH = int(os.getenv('KB_EXTRACT_BATCH', '128'))
KB_TOP_K = int(os.getenv('KB_TOP_K', '10'))
KB_EXTRACT_MAX_TOKENS = int(os.getenv('KB_EXTRACT_MAX_TOKENS', '4096'))
PREDICT_MAX_TOKENS = int(os.getenv('PREDICT_MAX_TOKENS', '1500'))
DISTILL_MAX_TOKENS = int(os.getenv('DISTILL_MAX_TOKENS', '600'))
EMBED_WORKERS = int(os.getenv('EMBED_WORKERS', '128'))
LLM_WORKERS = int(os.getenv('LLM_WORKERS', '128'))
LLM_MAX_RETRY = int(os.getenv('LLM_MAX_RETRY', '5'))
LLM_RETRY_BACKOFF = float(os.getenv('LLM_RETRY_BACKOFF', '1.5'))
DATA_DIR = str(BASE_DIR / 'data')
HYPERGRAPH_DIR = os.getenv('HYPERGRAPH_DIR', str(BASE_DIR / 'data' / 'hypergraph'))
EXPERIENCE_DIR = os.getenv('EXPERIENCE_DIR', str(BASE_DIR / 'data' / 'experience'))
EVENT_DIR = os.getenv('EVENT_DIR', str(BASE_DIR / 'data' / 'catalysts'))
KNOWLEDGE_FILES_DIR = os.getenv('KNOWLEDGE_FILES_DIR', str(BASE_DIR / 'knowledge_files'))
RESULTS_DIR = os.getenv('RESULTS_DIR', str(BASE_DIR / 'results'))
DATASET_DIR = os.getenv('DATASET_DIR', str(BASE_DIR / 'dataset'))
FOCAL_K = int(os.getenv('FOCAL_K', '1'))
CONTEXT_K = int(os.getenv('CONTEXT_K', '6'))
EXP_K = int(os.getenv('EXP_K', '5'))
EXP_MIN_SIM = float(os.getenv('EXP_MIN_SIM', '0.30'))
EXP_DOMAIN_BOOST = float(os.getenv('EXP_DOMAIN_BOOST', '0.0'))
SERPAPI_MAX_RESULTS = int(os.getenv('SERPAPI_MAX_RESULTS', '10'))
MAX_REASONING_ROUNDS = int(os.getenv('MAX_REASONING_ROUNDS', '5'))
ROLLOUT_N = int(os.getenv('ROLLOUT_N', '1'))
EXPERIENCE_TOP_K = int(os.getenv('EXPERIENCE_TOP_K', '5'))
CONFIDENCE_THRESHOLD = float(os.getenv('CONFIDENCE_THRESHOLD', '0.75'))
MAX_OUTER_LOOPS = int(os.getenv('MAX_OUTER_LOOPS', '3'))
COLLECT_ROUNDS_PER_PHASE = int(os.getenv('COLLECT_ROUNDS_PER_PHASE', '3'))
REASON_ROUNDS_PER_PHASE = int(os.getenv('REASON_ROUNDS_PER_PHASE', '1'))
WEB_HOST = os.getenv('WEB_HOST', '0.0.0.0')
WEB_PORT = int(os.getenv('WEB_PORT', '8765'))
C2F_L2_WINDOW_DAYS = int(os.getenv('C2F_L2_WINDOW_DAYS', '14'))
C2F_L3_WINDOW_DAYS = int(os.getenv('C2F_L3_WINDOW_DAYS', '90'))
C2F_L3_STEP_DAYS = int(os.getenv('C2F_L3_STEP_DAYS', '30'))
C2F_DETECT_CONF_THRESHOLD = float(os.getenv('C2F_DETECT_CONF_THRESHOLD', '0.7'))
C2F_DETECT_VOTES = int(os.getenv('C2F_DETECT_VOTES', '3'))
C2F_DETECT_VOTES_PASS = int(os.getenv('C2F_DETECT_VOTES_PASS', '1'))
C2F_L2_MAX_PER_WINDOW = int(os.getenv('C2F_L2_MAX_PER_WINDOW', '7'))
C2F_L3_MIN_STOCKS = int(os.getenv('C2F_L3_MIN_STOCKS', '2'))
C2F_L3_MIN_INDUSTRIES = int(os.getenv('C2F_L3_MIN_INDUSTRIES', '1'))
C2F_L3_MIN_CLUSTER_SIZE = int(os.getenv('C2F_L3_MIN_CLUSTER_SIZE', '2'))
C2F_L3_MAX_CLUSTER_SIZE = int(os.getenv('C2F_L3_MAX_CLUSTER_SIZE', '20'))
C2F_L3_DEDUP_COS_THRESHOLD = float(os.getenv('C2F_L3_DEDUP_COS_THRESHOLD', '0.85'))
C2F_L3_NAME_CONF_THRESHOLD = float(os.getenv('C2F_L3_NAME_CONF_THRESHOLD', '0.6'))
C2F_L3_MAX_THEMES_PER_DS = int(os.getenv('C2F_L3_MAX_THEMES_PER_DS', '200'))
C2F_RETRIEVE_K_L1 = int(os.getenv('C2F_RETRIEVE_K_L1', '3'))
C2F_RETRIEVE_K_L2 = int(os.getenv('C2F_RETRIEVE_K_L2', '3'))
C2F_RETRIEVE_K_L3 = int(os.getenv('C2F_RETRIEVE_K_L3', '2'))
CSM_STABILITY_K = int(os.getenv('CSM_STABILITY_K', '20'))
CSM_STABILITY_SEED = int(os.getenv('CSM_STABILITY_SEED', '42'))
CSM_STABILITY_STABLE_THRESHOLD = float(os.getenv('CSM_STABILITY_STABLE_THRESHOLD', '0.7'))
CSM_STABILITY_MISS_THRESHOLD = float(os.getenv('CSM_STABILITY_MISS_THRESHOLD', '0.3'))
CSM_STABILITY_SKIP_RATIO_LIMIT = float(os.getenv('CSM_STABILITY_SKIP_RATIO_LIMIT', '0.7'))
CSM_STABILITY_WEIGHT_MAP = {'stable': 1.2, 'unstable': 0.7, 'unevaluable': 1.0, 'miss': 0.0}
SCMR_K_PATHS = int(os.getenv('SCMR_K_PATHS', '3'))
SCMR_FALLBACK_TO_SINGLE = os.getenv('SCMR_FALLBACK_TO_SINGLE', '1') == '1'
GLOBAL_SEED = int(os.getenv('GLOBAL_SEED', '42'))
PROMPT_VERSION = os.getenv('PROMPT_VERSION', 'v1.0')
USE_C2F = os.getenv('TIER_USE_C2F', '0') == '1'
USE_CSM = os.getenv('TIER_USE_CSM', '0') == '1'
USE_SCMR = os.getenv('TIER_USE_SCMR', '0') == '1'
PIT_OFF = os.getenv('TIER_PIT_OFF', '0') == '1'
